// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainService.Data;

#nullable disable

namespace TrainService.Migrations
{
    [DbContext(typeof(TrainDbContext))]
    [Migration("20260909093453_SeedTrainDemoData")]
    partial class SeedTrainDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainService.Entities.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CoachType")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachNumber = "G1",
                            CoachType = 0,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 2,
                            CoachNumber = "S1",
                            CoachType = 1,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 3,
                            CoachNumber = "A3-1",
                            CoachType = 2,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 4,
                            CoachNumber = "S1",
                            CoachType = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 5,
                            CoachNumber = "A2-1",
                            CoachType = 3,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 6,
                            CoachNumber = "A1-1",
                            CoachType = 4,
                            TrainId = 2
                        });
                });

            modelBuilder.Entity("TrainService.Entities.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoachType")
                        .HasColumnType("int");

                    b.Property<int>("FromStationId")
                        .HasColumnType("int");

                    b.Property<int>("ToStationId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("Fares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 250.00m,
                            CoachType = 0,
                            FromStationId = 1,
                            ToStationId = 3,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 450.00m,
                            CoachType = 1,
                            FromStationId = 1,
                            ToStationId = 3,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 750.00m,
                            CoachType = 2,
                            FromStationId = 1,
                            ToStationId = 3,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 250.00m,
                            CoachType = 0,
                            FromStationId = 2,
                            ToStationId = 4,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 450.00m,
                            CoachType = 1,
                            FromStationId = 2,
                            ToStationId = 4,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 750.00m,
                            CoachType = 2,
                            FromStationId = 2,
                            ToStationId = 4,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 250.00m,
                            CoachType = 0,
                            FromStationId = 3,
                            ToStationId = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 450.00m,
                            CoachType = 1,
                            FromStationId = 3,
                            ToStationId = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 750.00m,
                            CoachType = 2,
                            FromStationId = 3,
                            ToStationId = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 600.00m,
                            CoachType = 0,
                            FromStationId = 1,
                            ToStationId = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 1000.00m,
                            CoachType = 1,
                            FromStationId = 1,
                            ToStationId = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 1600.00m,
                            CoachType = 2,
                            FromStationId = 1,
                            ToStationId = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 450.00m,
                            CoachType = 1,
                            FromStationId = 5,
                            ToStationId = 3,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1100.00m,
                            CoachType = 3,
                            FromStationId = 5,
                            ToStationId = 3,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 1800.00m,
                            CoachType = 4,
                            FromStationId = 5,
                            ToStationId = 3,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 450.00m,
                            CoachType = 1,
                            FromStationId = 4,
                            ToStationId = 2,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 1100.00m,
                            CoachType = 3,
                            FromStationId = 4,
                            ToStationId = 2,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 1800.00m,
                            CoachType = 4,
                            FromStationId = 4,
                            ToStationId = 2,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 450.00m,
                            CoachType = 1,
                            FromStationId = 3,
                            ToStationId = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 1100.00m,
                            CoachType = 3,
                            FromStationId = 3,
                            ToStationId = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 21,
                            Amount = 1800.00m,
                            CoachType = 4,
                            FromStationId = 3,
                            ToStationId = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1000.00m,
                            CoachType = 1,
                            FromStationId = 5,
                            ToStationId = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 23,
                            Amount = 2100.00m,
                            CoachType = 3,
                            FromStationId = 5,
                            ToStationId = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 24,
                            Amount = 3200.00m,
                            CoachType = 4,
                            FromStationId = 5,
                            ToStationId = 1,
                            TrainId = 2
                        });
                });

            modelBuilder.Entity("TrainService.Entities.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainId");

                    b.ToTable("RouteStops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new TimeSpan(0, 6, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 6, 0, 0, 0),
                            StationId = 1,
                            StopOrder = 1,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new TimeSpan(0, 7, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 7, 35, 0, 0),
                            StationId = 2,
                            StopOrder = 2,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new TimeSpan(0, 9, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 5, 0, 0),
                            StationId = 3,
                            StopOrder = 3,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 35, 0, 0),
                            StationId = 4,
                            StopOrder = 4,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new TimeSpan(0, 12, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            StationId = 5,
                            StopOrder = 5,
                            TrainId = 1
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new TimeSpan(0, 14, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 14, 0, 0, 0),
                            StationId = 5,
                            StopOrder = 1,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new TimeSpan(0, 15, 25, 0, 0),
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            StationId = 4,
                            StopOrder = 2,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new TimeSpan(0, 17, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 17, 5, 0, 0),
                            StationId = 3,
                            StopOrder = 3,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = new TimeSpan(0, 18, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 18, 35, 0, 0),
                            StationId = 2,
                            StopOrder = 4,
                            TrainId = 2
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = new TimeSpan(0, 20, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 20, 0, 0, 0),
                            StationId = 1,
                            StopOrder = 5,
                            TrainId = 2
                        });
                });

            modelBuilder.Entity("TrainService.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = 1,
                            SeatNumber = "1"
                        },
                        new
                        {
                            Id = 2,
                            CoachId = 1,
                            SeatNumber = "2"
                        },
                        new
                        {
                            Id = 3,
                            CoachId = 1,
                            SeatNumber = "3"
                        },
                        new
                        {
                            Id = 4,
                            CoachId = 1,
                            SeatNumber = "4"
                        },
                        new
                        {
                            Id = 5,
                            CoachId = 2,
                            SeatNumber = "1"
                        },
                        new
                        {
                            Id = 6,
                            CoachId = 2,
                            SeatNumber = "2"
                        },
                        new
                        {
                            Id = 7,
                            CoachId = 2,
                            SeatNumber = "3"
                        },
                        new
                        {
                            Id = 8,
                            CoachId = 2,
                            SeatNumber = "4"
                        },
                        new
                        {
                            Id = 9,
                            CoachId = 3,
                            SeatNumber = "1"
                        },
                        new
                        {
                            Id = 10,
                            CoachId = 3,
                            SeatNumber = "2"
                        },
                        new
                        {
                            Id = 11,
                            CoachId = 3,
                            SeatNumber = "3"
                        },
                        new
                        {
                            Id = 12,
                            CoachId = 3,
                            SeatNumber = "4"
                        },
                        new
                        {
                            Id = 13,
                            CoachId = 4,
                            SeatNumber = "1"
                        },
                        new
                        {
                            Id = 14,
                            CoachId = 4,
                            SeatNumber = "2"
                        },
                        new
                        {
                            Id = 15,
                            CoachId = 4,
                            SeatNumber = "3"
                        },
                        new
                        {
                            Id = 16,
                            CoachId = 4,
                            SeatNumber = "4"
                        },
                        new
                        {
                            Id = 17,
                            CoachId = 5,
                            SeatNumber = "1"
                        },
                        new
                        {
                            Id = 18,
                            CoachId = 5,
                            SeatNumber = "2"
                        },
                        new
                        {
                            Id = 19,
                            CoachId = 5,
                            SeatNumber = "3"
                        },
                        new
                        {
                            Id = 20,
                            CoachId = 5,
                            SeatNumber = "4"
                        },
                        new
                        {
                            Id = 21,
                            CoachId = 6,
                            SeatNumber = "1"
                        },
                        new
                        {
                            Id = 22,
                            CoachId = 6,
                            SeatNumber = "2"
                        },
                        new
                        {
                            Id = 23,
                            CoachId = 6,
                            SeatNumber = "3"
                        },
                        new
                        {
                            Id = 24,
                            CoachId = 6,
                            SeatNumber = "4"
                        });
                });

            modelBuilder.Entity("TrainService.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ALP",
                            Name = "Alpha Junction"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BRV",
                            Name = "Bravo Central"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CRN",
                            Name = "Charlie Town"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DLT",
                            Name = "Delta City"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ECH",
                            Name = "Echo Terminal"
                        });
                });

            modelBuilder.Entity("TrainService.Entities.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TrainNumber")
                        .IsUnique();

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Northern Express",
                            TrainNumber = "12001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Southern Express",
                            TrainNumber = "12002"
                        });
                });

            modelBuilder.Entity("TrainService.Entities.Coach", b =>
                {
                    b.HasOne("TrainService.Entities.Train", null)
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainService.Entities.Fare", b =>
                {
                    b.HasOne("TrainService.Entities.Train", null)
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainService.Entities.RouteStop", b =>
                {
                    b.HasOne("TrainService.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainService.Entities.Train", null)
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainService.Entities.Seat", b =>
                {
                    b.HasOne("TrainService.Entities.Coach", null)
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
